### ISSUE TITLE
Operation cancelled

### ISSUE THREAD

**Issue by tiptronic** [ashgan-dev/synology_ddns#1]
Hi there,
I just tried your script, but it throws an error (after quite some time showing the progress wheel).

Could it be, it throws an error, because my ip didn't change?

I also tried some basic entries (see below) in ddns_provider.conf - which also didn't work, but from my understanding these should work too.

Any idea?

thx

andy

```
[NSUpdate]
        modulepath=DynDNS
        queryurl=https://__HOSTNAME__:__PASSWORD__@ipv4.nsupdate.info/nic/update
        
[NSUpdate]
        modulepath=DynDNS
        queryurl=https://__USERNAME__:__PASSWORD__@ipv4.nsupdate.info/nic/update?hostname=__HOSTNAME__
```

**Comment by ashgan-dev** [comment]
@tiptronic on the nsupdate section, you should end up with this:
```
modulepath=/usr/syno/bin/ddns/nsupdate_info.php
queryurl=https://__HOSTNAME__:__PASSWORD__@ipv4.nsupdate.info/nic/update
```
and not a
```
modulepath=DynDNS
```
Also, be sure to upload my php file on /usr/syno/bin/ddns/nsupdate_info.php and make it executable.

dyndns and nsupdate don't work exactly the same way, that's why you have an error and a never ending progress wheel

**Comment by tiptronic** [comment]
@ashgan-dev : Sorry for the confusion - that's what I actually did:
```
[nsupdate.info]
    modulepath=/usr/syno/bin/ddns/nsupdate_info.php
    queryurl=https://__HOSTNAME__:__PASSWORD__@ipv4.nsupdate.info/nic/update
```
- file is executable  

I *also* tried the settings above using their default DynDNS module  

(and I think we should decide on one github repo for discussion ;))

**Comment by ashgan-dev** [comment]
@tiptronic you're right :) let's stick to this repo?

i'm not near my syno right now, so I will have more infos tonight.
that said, my script and install are pretty straightforward.

a few things come to my mind:
is root the owner of the php file?

editing of ddns_providers.conf provide you the nsupdate choice.

the bad wheel shows up only with incorrects parameters on the pannel settings or if the syno can't deal with the php file.
did you check your fields in the syno ddns pannel, as I wrote it?
don't forget that the secret key change every time you show the config on nsupdate website.

which syno do you have? 
I only have a DS414j, and this script really work fine for months (I still need to re-roll the whole thing after major updates). maybe things are differents on others models, by I can't see why.

**Comment by tiptronic** [comment]
Boah... there were 2 errors:
- first a stupid typo when creating the file (nsupdte_info.php vs. nsupdate_info.php -> try to find that in your console ;))
- second problem was that you added a open_basedir directive to the top of the php, which was not in my paths. Adding */usr/syno/bin/ddns/* to the allowed paths made it work fine! Maybe you want to add that to your Readme. (sorry I'm not a php-guy so I first had to figure out what's going on there...)

Now everything works fine (still have to find out how to add iPv6 to the script, though ;))

Good reminder on system updates: I think I will create a short script before the next update, which adds my DDNS configurations.

thx again for your kind help

andy
btw: I have a Syno 409 and 412+;

**Comment by ashgan-dev** [comment]
@tiptronic glad you nailed it!

 for the record, I'm not PHP guy neither. I have just copied an existing Synology file (the dyndns one, if I remember well) and mess around 'till this works :)
I can't help on IPv6, thanks to lame ISP.

for system updates, it won't happens everytimes. I can remember a samba update some times ago, my scripts were left fine.
but yes, better to remember.

**Comment by tiptronic** [comment]
@ashgan-dev Great! 2 Non-PHP-guys talking about php... - not too bad ;)
Cheers
